# Generated by Django 5.1 on 2024-09-03 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_short_i_e9ca75_idx',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created'], name='profiles_pr_created_39264b_idx'),
        ),
    ]
