# Generated by Django 5.1 on 2024-08-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'technologies'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commenter',
        ),
    ]
