# Generated by Django 5.1 on 2024-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_options_and_more'),
        ('projects', '0004_alter_review_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='projects_ta_created_9ea01a_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title', 'description'], name='projects_pr_title_4ec0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='projects_ta_name_536b15_idx'),
        ),
    ]
