# Generated by Django 5.1 on 2024-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_options_alter_skill_options_and_more'),
        ('projects', '0005_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated',
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Demo Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='featured_image/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source Code Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(default=0, verbose_name='Vote Ratio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vote_total',
            field=models.IntegerField(default=0, verbose_name='Vote Total'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created'], name='projects_pr_created_5ace3f_idx'),
        ),
    ]
