# Generated by Django 5.1 on 2024-08-23 14:11

import apps.accounts.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=autoslug.fields.AutoSlugField(always_update=True, default='praise-id', editable=False, populate_from=apps.accounts.models.slugify_two_fields, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
