# Generated by Django 5.1 on 2024-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_active',
            field=models.BooleanField(default=True),
        ),
    ]
