# Generated by Django 5.1 on 2024-09-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user_active',
            new_name='user_active',
        ),
    ]
