# Generated by Django 5.1.1 on 2025-11-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_body_alter_message_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
